### ISSUE TITLE
Playbook sets NAS user's primary group to `docker` instead of adding them to that group

### ISSUE THREAD

**Issue by codebrewer** [davestephens/ansible-nas#169]
`tasks/docker.yml` contains:

```
- name: add user account to docker group
  user:
    name: "{{ ansible_nas_user }}"
    group: docker
    append: yes
```

Note `group` rather than `groups`. The result is that instead of adding the user to the `docker` group their primary group is changed to `docker`.
