### ISSUE TITLE
Setting a feature to enabled: false doesn't stop the container if previously installed

### ISSUE THREAD

**Issue by bcurran3** [davestephens/ansible-nas#207]
Setting a previously enabled application as false should should stop the container on subsequent runs of the playbook. Currently it continues running.

**Comment by davestephens** [comment]
This is actually something I've had in my head to fix for a while, I just need to come up with a clean way to do it.

**Comment by animeai** [comment]
The simple fix is to add code similar to:
`name: Remove Old Sickrage Docker Container
docker_container:
name: sickrage
state: absent
keep_volumes: true`
Put within an if function at the top of every /tasks/*.yml so it runs if the container is set to "false". This is inelegant though and would be better addressed by a single task that runs at the start of the playbook that shuts down all containers that are set to false.

**Comment by bcurran3** [comment]
I thought that task didn't run unless it was set to enabled?

Example from nas.yml:

  - import_tasks: tasks/openhab.yml
    when: (openhab_enabled | default(False))
    tags: openhab

I'm still new to this so maybe I'm wrong...

..but I would think any cleanup would need to happen in nas.yml

**Comment by animeai** [comment]
To extrapolate on my initial remark, the tasks would need to be run every time and the rest wrapped in an "if true" statement - as I said, inelegant.

**Comment by davestephens** [comment]
Yep, that's correct, and it would probably need to be rejigged somehow to
cater for stopping containers (and also why I've not tackled it yet 😁)

**Comment by bcurran3** [comment]
I don't understand why you couldn't just add a docker stop command for each task in nas.yml when the container is flagged as not enabled?

**Comment by davestephens** [comment]
Because DRY. I'd like to do it elegantly.

**Comment by bcurran3** [comment]
I'm not a DRY follower. I'm a GBB follower. Make it good (work). Make it Better. Make it Best.

What is required to do it elegantly to your satisfaction?

**Comment by bcurran3** [comment]
@davestephens Still would like to know your requirements on doing it gracefully... i.e. I can't try to move forward on this without some sort of direction/guidance to do it right.

**Comment by PurpleNinja225** [comment]
We could maybe add a post_tasks script that checked for which ```{{ application }}_enabled: true``` and flush any docker applications matching false :thinking:

**Comment by davestephens** [comment]
Yeah, it's something I've been thinking about in the background as it'd be
nice to have!

Few thoughts:

- Right now applications are turned on/off at the role level, so having a
stop task within the role currently isn't possible. If it wasn't, would we
want to do this? Feels a bit messy.

- We could have a role at the end of execution that stops all the things
that shouldn't be running. If we did this, how would that role determine
things that should be switched off? Presumably by looking at all the
*_enabled variables and doing something with the ones that are set to `no`.
How would all or those variables be collected up to be acted upon?

- Something else entirely I've not considered?

**Comment by bcurran3** [comment]
I've got a cleanup.yml task inserted at the end of my nas.yml that handles this. Simply the code below for each app.

```
- name: organizr stop if disabled but running
  ignore_errors: true
  docker_container:
    name: organizr
    state: stopped
  when: organizr_enabled == false
```

**Comment by PurpleNinja225** [comment]
Since the role is only imported if ```{{ application }}_enabled: true``` that task would never run (i think). However putting at the end of the main nas.yml still worked. I'm down for a solution like this if we can get it to loop the enabled applications because implementing as is would make nas.yml another 30% longer.

**Comment by PurpleNinja225** [comment]
quick and dirty, but this should do the trick

```yml
  - name: Cleanup no longer used Applications
    docker_container:
      name: "{{ item.name }}"
      state: absent
    when: "{{ item.enabled }} == false"
    loop:
      - { name: 'pyload', enabled: 'pyload_enabled' }
      - { name: 'mylar', enabled: 'mylar_enabled' }
      - { name: 'jackett', enabled: 'jackett_enabled' }
      - { name: 'nzbget', enabled: 'nzbget_enabled' }
      - { name: 'airsonic', enabled: 'airsonic_enabled' }
```
