### ISSUE TITLE
Any tips on creating Samba Users?

### ISSUE THREAD

**Issue by DLLarson** [davestephens/ansible-nas#225]
Hi, I'm back! ;)

I'm trying to create samba users in my `nas.yml` file using the `bertvv.samba` role and it always fails. Here is what I'm providing as a test (a link to my complete file is given below):

```yaml
samba_users:
  - name: dlarson
    password: foobar
```

It causes the following error when running the playbook:

```
TASK [bertvv.samba : Create Samba users if they don't exist yet] **************************************************************************************************************************
failed: [ansible-nas] (item=None) => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}
fatal: [ansible-nas]: FAILED! => {"censored": "the output has been hidden due to the fact that 'no_log: true' was specified for this result", "changed": false}

PLAY RECAP ********************************************************************************************************************************************************************************
ansible-nas                : ok=10   changed=0    unreachable=0    failed=1
```

I put `no_log: false` at the top of my `nas.yml` file but it had no effect on the error output.

At first I was trying to hide the password with ansible-vault:

```yaml
dlarson_passwd: !vault |
          $ANSIBLE_VAULT;1.1;AES256
          30613861656134343330396436386432346131376434613837343939383336373935393161363666
          3338373432653536653236346633366162666638393163640a666632373732343736653633363439
          36306665333736616337323335393365613434356336313065316261363333396561393333383566
          3039373633633537320a313136333961386139376431666463653131373234313261386363353434
          3532
# : 
# : 
samba_users:
  - name: dlarson
    password: "{{ larzmedia_passwd }}"
```

I figured that was the issue. But the simple example provided first also fails with the password given in plain text so I don't think that's the problem.

Note also that when I tried to create a linux user account using the following specification it failed as well:

```yaml
- name: Create user dlarson
  user:
    name: dlarson
    state: present
    update_password: on_create
    create_home: no
    password: "$6$.gijCVAXbENBqQ$iDfsr2vMB8o2G.e.as18Q1jsLhix7DOs.7MUQkmWHU2zF0yhqMGwd1rT.X7e3knGq4/5KIfsV21Pe02nd4yJv0"
    group: dlarson
    shell: /usr/sbin/nologin
```

In that case I get the following error:

```
PLAY [all] ********************************************************************************************************************************************************************************
ERROR! Syntax Error while loading YAML.
  did not find expected key

The error appears to have been in '/home/skb/ansible-nas/inventories/my-ansible-nas/group_vars/nas.yml': line 27, column 1, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Create user dlarson
^ here

```

The above linux user definition is patterned after the task file `tasks/users.yml`.

Here's a link to my full `nas.yml` file:

https://github.com/DLLarson/ansible-nas/blob/master/inventories/my-ansible-nas/group_vars/nas.yml

Is it possible that these operations are not allowed in the `nas.yml` file?

-Dale
