### ISSUE TITLE
Need Help With Traefik Let's Encrypt Support

### ISSUE THREAD

**Issue by DLLarson** [davestephens/ansible-nas#230]
Hi,

I have my own domain named `dilbertshrugged.com` managed via GoDaddy.com.

As a first test I'm trying to make Gitea available from outside my NATted router (I use Google Wifi.)

You can see my Ansible settings for this here:

https://github.com/DLLarson/my-ansible-nas/blob/master/inventories/localhost/group_vars/nas.yml

Essentials are excerpted here:

```yaml
# Enable the reverse proxy for external access.
traefik_enabled: true

# System options.
ansible_nas_email: dlarson42@gmail.com
ansible_nas_domain: dilbertshrugged.com

# Gitea defn's
gitea_enabled: true
gitea_data_directory: "{{ zfs_root }}/gitdata"
gitea_available_externally: "true"
```
When I try to access the site with domain `gitea.dilbertshrugged.com` I get the usual browser error that the site has a bad certificate. This implies to me that no Let's Encrypt processing magically happened.

One thing I did NOT do was to register `*.dilbertshrugged.com` in my DNS definitions as the Ansible NAS documentation suggests. I just defined a new `gitea` CNAME. It seems to me that setting a wild card domain lookup would map *all* access to the domain to my router IP. I definitely don't want that. Am I wrong here? If I am, what type of DNS record would I use to do it?

I'm at a loss with how to diagnose this functionality. I looked at the traefik log using Portainer and see no logs of me accessing the proxy but yet, if I allow the browser to proceed past the error, I do get the Gitea site. (Although it won't configure due to some mysql issue...but that's a different problem.)

Any tips would be greatly appreciated!

-Dale
