### ISSUE TITLE
Add cloudflared

### ISSUE THREAD

**Issue by HitLuca** [davestephens/ansible-nas#522]
Useful for creating direct tunnels to couldflare endpoints, allows the user to set up public services while behind CG NAT and similar. Contrarily to cloudflare dynamic dns,  this container would allow putting ansible-nas services on the internet on demand (turn on or off the cloudflared app), since the only point of access would be provided by this container.

This involves some setup first, since you need to:

- get a cloudflare domain purchased
- create a cloudflare tunnel to use from your machine
- add DNS rules to connect your machine to the cloudflare domain using the cloudflare tunnel
- save the configuration data to a known folder, to be mapped inside the container for use

More info for the setup part on [this link](https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/private-net/#before-you-start). The cloudflared container can be used to do the login/auth/tunnel creation steps as well.

My setup currently uses this container, and the `docker-compose` I created in Portainer looks like this

```yaml
version: "2"
services:
  cloudflared:
    image: cloudflare/cloudflared:2022.1.2
    container_name: cloudflared
    environment:
      - TZ=${TZ}
    volumes:
      - /path_to_my_cloudflared_directory:home/nonroot/.cloudflared/
    restart: unless-stopped
    command: tunnel run ${TUNNEL_NAME}
    network_mode: host
 ```

Let me know if you need other info regarding my setup!
