### ISSUE TITLE
Add VSCode Server image

### ISSUE THREAD

**Issue by HitLuca** [davestephens/ansible-nas#534]
Used for remote development, I think this app would be a nice addition to this project.

The site for the docker image is [this](https://coder.com/docs/code-server/latest), and the setup guide for docker is [here](https://coder.com/docs/code-server/latest/install#docker).

The setup is pretty straightforward, In my case I created the container using Portainer, and mounted my projects folder from a zpool dataset. 

Here is my setup if it can help design the feature:

```yaml
version: '3.7' 
services: 
    vscode_server: 
        image: codercom/code-server
        container_name: vscode_server 
        restart: unless-stopped 
        ports:
            - 9050:8080 #<- the vscode image uses port 8080, so we need to change it since nextcloud uses it
        volumes: 
            - ${CONFIG_FOLDER}:/home/coder/.config
            - ${PROJECTS_FOLDER}:/home/coder/project
        environment: 
            - TZ=${TZ}
            - DOCKER_USER=$USER            
```
