### ISSUE TITLE
Bitwarden issue when setting bitwarden_allow_signups to true

### ISSUE THREAD

**Issue by HitLuca** [davestephens/ansible-nas#610]
looks like bitwarden errors out when `bitwarden_allow_signups` is set to `true` in the inventory file. The value should be casted as string as such

```yaml
---
    - name: Bitwarden Docker Container
      ...
        env:
          SIGNUPS_ALLOWED: "{{ bitwarden_allow_signups | string }}"
```
